version: 2.1

jobs:

  build:
    parameters:
      ruby-version:
        type: string

    docker:
      - image: cimg/ruby:<< parameters.ruby-version >>

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: |
            bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs=4 --retry=3

      - run:
          name: Run tests
          command: |
            bundle exec rspec --profile 10 \
                              --format RspecJunitFormatter \
                              --out /tmp/test-results/rspec.xml \
                              --format progress
workflows:
  build:
    jobs:
      - build:
          matrix:
            parameters:
              # https://github.com/CircleCI-Public/cimg-ruby
              # only supports the last three ruby versions
              ruby-version: ["2.7.7", "3.0", "3.1"]
