name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: [
          "2.7",
          "2.7.7",
          "2.7.8",
          "3.0",
          "3.1",
          "3.2",
          "3.3"
        ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Ruby ${{ matrix.ruby-version }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true

      - name: Run tests
        run: |
          bundle exec rspec \
            --profile 10 \
            --order random \
            --format RspecJunitFormatter \
            --out junit-xml-report-${{ matrix.ruby-version }}.xml \
            --format documentation \
            spec/

      - name: Test summary
        uses: test-summary/action@v2
        with:
          paths: junit-xml-report-${{ matrix.ruby-version }}.xml

